### ISSUE TITLE
Feature request: Pre-define zoom level

### ISSUE THREAD

**Issue by ituri** [hkgnp/logseq-osmmaps-plugin#1]
see above. 😊

**Comment by benjypng** [comment]
Hi, please follow the instructions below to have a pre-defined Zoom level for all the maps you create.

1. Uninstall the plugin that you have installed manually.

2. Close Logseq.

3. Go to `.logseq/settings` page and delete the file `logseq-osmmaps-plugin.json`.

4. Open Logseq.

5. Install the plugin from the marketplace.

6. Go to plugin settings by clicking the gear icon, and clicking "Go to settings".
<img width="305" alt="Screenshot 2022-01-18 at 12 30 03 PM" src="https://user-images.githubusercontent.com/47936793/149871231-73cf2c4b-0d90-49e8-953b-7d9688bc217a.png">

7. Copy and paste the code from below to the settings page and set the default zoom level that you would like.
```
{
    "defaultZoom": 13
}
```
8. Close Logseq.

9. Open Logseq.

10. You will see that the maps you create follow the default Zoom level that you set in Step 7.
