### ISSUE TITLE
display on the map

### ISSUE THREAD

**Issue by thebigalwisi** [hkgnp/logseq-osmmaps-plugin#11]
Hello @hkgnp, 

I have just displayed some places and I have noticed what I'm personally missing, maybe you could add these functions to your plugin, I think it would be useful not only for me..

- An option to show different places on the map with different icons and/or colours.
- A button to show the names of all places on the map at the same time and to turn them off.

**Comment by thebigalwisi** [comment]
No? No-one?

**Comment by benjypng** [comment]
I'm currently overseas. Will take a look when I am back.

**Comment by thebigalwisi** [comment]
Hi @hkgnp , 

I don't want to rush you, just to ask if and when we can expect the improvements mentioned above?

**Comment by benjypng** [comment]
Avaiable in the latest version.
