### ISSUE TITLE
Only markers at note's root level?

### ISSUE THREAD

**Issue by diegodlh** [hkgnp/logseq-osmmaps-plugin#13]
Hey! Thank you for this plugin!

I've just installed it today and started playing with it. It seems to recognize only markers at the note's root level. I mean, in the following example:

```
- {{renderer(:map_66bd4581-b45a-4257-bd72-3eea794a1577,10,Singapore)}}
- marker 1
  coords:: -35, -60
  - marker 2
    coords:: -35, -65
```

the map only shows the first marker, not the second one. Is this the intended behavior? Or am I getting something wrong?

Thank you!

**Comment by benjypng** [comment]
I think that currently is!

But you are right and it should ideally recognise all blocks, nested or not. 

I'll find some time to enhance it.

**Comment by diegodlh** [comment]
Thanks for your reply! Sure, no rush. I know what it is to maintain a piece of software voluntarily! Just wanted to make sure I wasn't missing something. I will be happy to test the improvements if you manage to make them some day! :)

**Comment by benjypng** [comment]
Thanks for your patience! It now supports recursive blocks :)
