### ISSUE TITLE
Feature request: Allow different basemaps

### ISSUE THREAD

**Issue by ituri** [hkgnp/logseq-osmmaps-plugin#2]
I want to use the plugin for different puproses, i.e. city trip planning or for planning hiking or cycling trips. It would be nice if I could select different basemaps for that.

**Comment by benjypng** [comment]
Apologies, what's a basemap?

**Comment by ituri** [comment]
I was thinking about the different map layers that you can select on openstreetmap.org or on other providers. Examples would be CyclOSM, the transport map etc.
![Screenshot 2022-01-18 at 08 46 23](https://user-images.githubusercontent.com/871297/149892912-fab09c85-1e40-4dfb-adc8-36362aa8d145.png)

**Comment by benjypng** [comment]
I see! Hmm, there seem to be quite many options. Can I check with you which of the maps are the most important to you?

Priority 1:
Priority 2:

**Comment by ituri** [comment]
Which provider are you using? Mapbox? Or are you pulling them directly from openstreetmap.org? I guess the choice also depends on the layers that the provider is offering.

A hiking map with focus on hiking trails and contour lines would be nice.

**Comment by benjypng** [comment]
I will probably use this: https://www.thunderforest.com/ but will also take a look at Mapbox. 

Caveat that the routing function may not find cycling or hiking routes though.

**Comment by ituri** [comment]
Okay. 😊 

Priority 1: OpenCyclemap
Priority 2: Outdoors

**Comment by benjypng** [comment]
https://twitter.com/hkgnp/status/1483433343815663622?s=21

**Comment by benjypng** [comment]
FR implemented in v1.5. Will close this issue now.

**Comment by ituri** [comment]
Thank you!
