### ISSUE TITLE
Add support for collection many point on a map

### ISSUE THREAD

**Issue by jaroet** [hkgnp/logseq-osmmaps-plugin#3]
Thanks for a great plugin.

I have used the Obsidian Map View plugin quite a lot to show all kind of location data on a map. But always with one map and many (or not so many) location points. 

So I could for instance create a map where I showed all the locations of my collegeas or the locations of the all restaurants I have been. 

A great feature would be if you could define a property like address:: to the map so the value of address was taken and a marker is shown on the map that on hoover shows the page name and when you click on it shows you the page or block it came from.
This way you can create different maps which you geo data of some importance to you. 

I realize this is quite a big thing to ask but I just wanted to put it out here as I do not know how to do it myself. 

For reference of the obsidian map view plugin see ... https://github.com/esm7/obsidian-map-view

**Comment by benjypng** [comment]
Hi! Thanks for the suggestion. I've got other requests for this as well. 

Yes it's on my roadmap but as the maps plugin requires some hacking will need to experiment to see what's the best way to do it and this may take time!

**Comment by benjypng** [comment]
[Available in the latest version](https://github.com/benjypng/logseq-osmmaps-plugin?tab=readme-ov-file#step-2).
