### ISSUE TITLE
adjust the settings in the "Plugin Settings" panel

### ISSUE THREAD

**Issue by charliie-dev** [hkgnp/logseq-osmmaps-plugin#4]
I recently found out that we can adjust the settings in the "Plugin Settings" panel.
 It would be nice to adjust the zoom settings in there. :)

**Comment by charliie-dev** [comment]
Also, if it's possible to set the zoom factor differently in each map?

**Comment by benjypng** [comment]
I am planning a refactor when I have the time and will try to incorporate your suggestions.

**Comment by charliie-dev** [comment]
Thanks!

**Comment by benjypng** [comment]
Available in the latest version.

Specifically [this](https://github.com/benjypng/logseq-osmmaps-plugin/blob/main/README.md#step-2).
