### ISSUE TITLE
Cannot read properties of undefined (reading 'coords')

### ISSUE THREAD

**Issue by dziurka** [hkgnp/logseq-osmmaps-plugin#5]
Thanks for a great plugin!

Unfortunately, the current version doesn't work for me. I'm getting the following error:

<img width="732" alt="image" src="https://user-images.githubusercontent.com/16003856/218278697-0b294d46-8981-4eec-9c38-85e59c243c53.png">
<img width="600" alt="image" src="https://user-images.githubusercontent.com/16003856/218278904-a134ff6e-950c-459c-9d69-cf2212e3c67d.png">

You probably just need to add the null safe operator:
```js
 if (pbt[i].properties!?.coords) {
```

**Comment by lef-est** [comment]
I'm seeing similar errors: 
![image](https://user-images.githubusercontent.com/9643637/228752861-c247cf2b-1e59-4a53-a06a-3cc4fc6fdeda.png)

I use org, though, not sure if that's the problem.
```
destination
:PROPERTIES:
:coords: x, y
:END:
```

**Comment by benjypng** [comment]
> Thanks for a great plugin!
> 
> Unfortunately, the current version doesn't work for me. I'm getting the following error:
> 
> <img alt="image" width="732" src="https://user-images.githubusercontent.com/16003856/218278697-0b294d46-8981-4eec-9c38-85e59c243c53.png">
> 
> <img alt="image" width="600" src="https://user-images.githubusercontent.com/16003856/218278904-a134ff6e-950c-459c-9d69-cf2212e3c67d.png">
> 
> You probably just need to add the null safe operator:
> 
> ```js
>  if (pbt[i].properties!?.coords) {
> ```

Should be fixed.

**Comment by benjypng** [comment]
> I'm seeing similar errors: ![image](https://user-images.githubusercontent.com/9643637/228752861-c247cf2b-1e59-4a53-a06a-3cc4fc6fdeda.png)
> 
> I use org, though, not sure if that's the problem.
> 
> ```
> destination
> :PROPERTIES:
> :coords: x, y
> :END:
> ```

Please try latest version.

**Comment by lef-est** [comment]
> > I'm seeing similar errors: ![image](https://user-images.githubusercontent.com/9643637/228752861-c247cf2b-1e59-4a53-a06a-3cc4fc6fdeda.png)
> > I use org, though, not sure if that's the problem.
> > ```
> > destination
> > :PROPERTIES:
> > :coords: x, y
> > :END:
> > ```
> 
> Please try latest version.

Thanks, it's working now!
