### ISSUE TITLE
Please improve  documentation for usage with queries

### ISSUE THREAD

**Issue by sgofferj** [hkgnp/logseq-osmmaps-plugin#8]
I can't get the plugin to show anything with queries. When researching, I found a forum topic which describes the exact same issue I have: https://discuss.logseq.com/t/use-osmmaps-plugin-with-query/17447

**Comment by benjypng** [comment]
Hi! Query to use will be:

```
{{query (property :coords)}}
```

Just place the above query in a page containing the map. You may add other query parameters, but it is important that you include `(property :coords)`.

I have also updated the `README` with this example. Thanks!
