### ISSUE TITLE
Add settings to display names on the map in English instead of local language 

### ISSUE THREAD

**Issue by slidingshade** [hkgnp/logseq-osmmaps-plugin#9]
Some country/street names are shown in the local language. Armenia example:
<img width="822" alt="Screenshot 2023-08-04 at 16 23 00" src="https://github.com/hkgnp/logseq-osmmaps-plugin/assets/3026704/86716883-2360-4e0c-b705-17336878ebec">
Looks like it depends on tiles server you're using, https://stackoverflow.com/questions/18589621/setting-map-language-to-english-in-openstreetmap-with-leafletjs

**Comment by benjypng** [comment]
You can change the default tilelayer URL in the latest version (from the plugin settings).
